version: "3.3"

services:
  postgres:
    image: postgres:16
    container_name: dashboard-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: dashboard
      POSTGRES_USER: dashboard
      POSTGRES_PASSWORD: dashboard_strong_password
      TZ: Asia/Jakarta
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "127.0.0.1:5432:5432"

  dashboard:
    build: .
    container_name: dashboard-isp
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8001:8000"
environment:
  FLASK_SECRET_KEY: "0b8dbb3d82a3794f019594373d49f9f59c5dfc96f3f781bc0b4b99e397494540"

volumes:
  pgdata:
